name: Build & Release BBtool GUI

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest]
        python-version: ['3.12']

    env:
      APP_NAME: 'bbtool'

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade "pip<24.1" || echo "跳过 pip 升级"
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build executable
        run: python build.py

      - name: Rename and move binary
        run: |
          mkdir -p release
          cp dist/${{ env.APP_NAME }}* release/ || cp dist/* release/

      - name: Upload to GitHub Releases
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          files: release/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
