name: Build & Release BBtool GUI

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    env:
      PYTHON_VERSION: '3.10'
      APP_NAME: 'bbtool'

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: |
          pip3 install --upgrade pip
          pip3 install -r requirements.txt
          pip3 install pyinstaller

      - name: Build executable
        run: python3 build.py

      - name: Rename and move binary
        run: |
          mkdir -p release
          cp dist/${{ env.APP_NAME }}* release/

      - name: Upload to GitHub Releases
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          files: release/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
